### ISSUE TITLE
Is it possible to hide the filename in dataview table?

### ISSUE THREAD

**Issue by terrychenzw** [scottwillmoore/obsidian-short-links#9]
thanks for your excellent work for this plugin.

I would like to know Is it possible to hide the filename in dataview table?

![image](https://github.com/scottwillmoore/obsidian-short-links/assets/114856910/87ad22f7-56df-45b2-be07-8d854bb0d6ac)

**Comment by scottwillmoore** [comment]
I think this should be fixed now!

**Comment by terrychenzw** [comment]
Thanks for your prompt response. But it doesn't work. I am not sure if my setting is correct.
![short link issue](https://github.com/scottwillmoore/obsidian-short-links/assets/114856910/4531d979-02c7-4acc-969d-0c5047ac906b)

**Comment by scottwillmoore** [comment]
Just to double check you did update your plugins (the latest version should be 1.1.3) and then restart/reload Obsidian? Given that you do have version 1.1.3 of this plugin installed, and it still is not working it would be super helpful if you could upload your test Markdown files/vault.

**Comment by terrychenzw** [comment]
> Just to double check you did update your plugins (the latest version should be 1.1.3) and then restart/reload Obsidian? Given that you do have version 1.1.3 of this plugin installed, and it still is not working it would be super helpful if you could upload your test Markdown files/vault.

yes, i have upgraded the version to 1.1.3, and reload Obsidian. below is my MD files. thanks a lot.

[test file.md](https://github.com/scottwillmoore/obsidian-short-links/files/11845250/test.file.md)

**Comment by scottwillmoore** [comment]
Okay, so I have done some more investigation. Obsidian doesn't provide an easy way to detect if a link is an alias or not when in rendered Markdown. I have a "hack" which does work, and thought you might have found an edge case.

But, it turns out that the links that are [generated by the Dataview plugin](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/data-model/value.ts#L546) are all aliases... In other words all links generated by the Dataview plugin are of the form `[[<LINK-PATH>|<LINK-ALIAS>]]` instead of just `[[<LINK-PATH>]]`. Therefore, my plugin doesn't make any changes to the link text as to preserve aliases.

So... I think this might be an issue that needs to be raised with the Dataview plugin. The exact line of code is in [this else statement](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/data-model/value.ts#L546), whereby they should probably not generated an alias and leave that for Obsidian and my plugin to do.

I'll log an issue with the Dataview plugin, but it could take some time for them to fix.

**Comment by terrychenzw** [comment]
As i re-installed and tested the earlier version of short-link("version": "1.0.2", "minAppVersion": "0.16.0"). it works!!

<img width="709" alt="企业微信截图_16875315072764" src="https://github.com/scottwillmoore/obsidian-short-links/assets/114856910/b28da41d-179f-4290-a92c-3e354fea7c5d">
